apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/crud-web-apps/jupyter/manifests/overlays/istio?ref=v1.6.0-rc.0

patchesStrategicMerge:
- spawner_ui_config.yaml
- logos-configmap.yaml

images:
- name: docker.io/kubeflownotebookswg/jupyter-web-app
  newName: docker.io/kubeflownotebookswg/jupyter-web-app
  newTag: v1.6.0-rc.0
