apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radosgw-ingressgateway-certs
  namespace: rook-ceph
spec:
  secretName: radosgw-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  commonName: rgw.my-cluster.my-domain.com
  dnsNames:
    - rgw.my-cluster.my-domain.com
    - '*.rgw.my-cluster.my-domain.com'
