apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-trust
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v0.1.1
    chart: cert-manager-trust
    helm:
      parameters:
        - name: app.trust.namespace
          value: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
