apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wutb15/argoflow.git
    targetRevision: test-flow
    path: distribution/kubecost-resources
    kustomize:
      version: v4.5.5
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
