apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
    # 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
      - name: custom-tools
        emptyDir: {}
      # 2. Use an init container to download/copy custom binaries into the emptyDir
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        args:
        - wget -qO- https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.5/kustomize_v4.5.5_linux_amd64.tar.gz | tar -xvzf - &&
          mv kustomize /custom-tools/kustomize_4_5_5
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
        env:
        - name: http_proxy
          value: http://192.168.1.3:7890/
        - name: HTTPS_PROXY
          value: http://192.168.1.3:7890/
        - name: https_proxy
          value: http://192.168.1.3:7890/
        - name: NO_PROXY
          value: 172.18.0.0/16,fc00:f853:ccd:e793::/64,localhost,127.0.0.0/8,::1,10.96.0.0/16,10.244.0.0/16,kind-control-plane,kind-control-plane2,kind-control-plane3,kind-worker,kind-worker2,kind-worker3,kind-external-load-balancer,.svc,.svc.cluster,.svc.cluster.local
        - name: no_proxy
          value: 172.18.0.0/16,fc00:f853:ccd:e793::/64,localhost,127.0.0.0/8,::1,10.96.0.0/16,10.244.0.0/16,kind-control-plane,kind-control-plane2,kind-control-plane3,kind-worker,kind-worker2,kind-worker3,kind-external-load-balancer,.svc,.svc.cluster,.svc.cluster.local
        - name: HTTP_PROXY
          value: http://192.168.1.3:7890/
      # 3. Volume mount the custom-tools directory to the repo-server
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
        env:
        - name: http_proxy
          value: http://192.168.1.3:7890/
        - name: HTTPS_PROXY
          value: http://192.168.1.3:7890/
        - name: https_proxy
          value: http://192.168.1.3:7890/
        - name: NO_PROXY
          value: 172.18.0.0/16,fc00:f853:ccd:e793::/64,localhost,127.0.0.0/8,::1,10.96.0.0/16,10.244.0.0/16,kind-control-plane,kind-control-plane2,kind-control-plane3,kind-worker,kind-worker2,kind-worker3,kind-external-load-balancer,.svc,.svc.cluster,.svc.cluster.local
        - name: no_proxy
          value: 172.18.0.0/16,fc00:f853:ccd:e793::/64,localhost,127.0.0.0/8,::1,10.96.0.0/16,10.244.0.0/16,kind-control-plane,kind-control-plane2,kind-control-plane3,kind-worker,kind-worker2,kind-worker3,kind-external-load-balancer,.svc,.svc.cluster,.svc.cluster.local
        - name: HTTP_PROXY
          value: http://192.168.1.3:7890/
