kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgCjysYVDQRMNGi0nQgQTFdMzKOJ82FDdTofc7gQ4FQauxINdx7NjAh8g3SmWowBUr+OU2cyHK3evud8jr13NNdRL8DuqotJNg9m7Y28ke/d+eBz9THLr7FPd63Zuz3sSpiGBgL/heZdOCES37c+BdI7tVXHKKpnHGFFUFpjkdZsupB43unznyWRsxFa1iZas12zYjhRTXR8aoPA/2Ieg4ClJRf2tG5Rz2lKcvxwgGQUBCzhgajlFfgDChkfHZCsK6hgBXE3VXkdmmXN6gh3IIl/9MfLnnb94bewnjPOn/Y+GEsNiAeW+rovFUyoZy5YY08OYOAEngT7zfN7zCzhHRYMzKPSU9Q/bVOuDPwRXIvdwACITm+xmmvqRgS59hgOIdOokGG6oNgZp+AdaoIxvK1INPWz3I8BtJ//9dW/cUn7FG9WkarQW5K/WEA0A4gYTTmFe+ltsrsH2mgP9U68NM2k6b8kYkkVA8F8+j1fb8rsheKmbixTcjdTeoe9q65KS3z1xcHiioFYTca5PzjVt7kGVkxsaIitLi7Ukmd3sYOxCf07OXL8+74waKWXIPhHq4GIlGZDNLlu0XvHDJJPfxlOOCIL9ujV74EG4KXK6mbZJhQbAYcCJN7LDZoNpmOPSwwxZzhFuwlKo01/ZkQ8cXGan5seo/88+axwklcA09e+gbfaH2XIVNBnsoenhN6KXzW4PnGSCxxOakZa1bAWQOGhYz+dM+8RDaw75v9FSTTBmw==
    postgresql-postgres-password: AgAogMgHYDt4JjGaD96Rqse/OvZu9tGk5+qygE2kvNpU1zr6Khdnyes5HgG0gIdkEk13EidHk/ppMzfSu6DexCsz6prtqlYaAsFPLcH+tcxD/aEkGya1G3TW3CDffYRD5vcMYS++/qtbcGuwhH2ZSYWpPw8IKscI2gluTrbZ6vWf06/70Lp3HmFKAO9NkTqrR0YmbbcqqKhwN48oRwv9JciVVRc9/XFjTiBAEmBzRGsGHETPUHDius4zpCBIWhtEJh1LrTn2u49eEyGi1QZmXIAu6VqXabXdYuEMpfpBpiCyPNgNI7A3BYskp6u5xdhK8O9od6kTV6E/tHrZ8i1SUL2Z8l2Fn27PGCis1JrRAQz5qe1Nza/n+NCo0rVMYYxn56q5Gbiem7vg+tGlLAQDtrgeJfHCInB8B6BVmmpgnEtdMUk6dE+RH9eSMMlINLQc4397foU7BlDZvtff5hxc+5D6AGt5sXHz2JXtC6v3cnuxsifWUqNhapra5aNjmPu01L0GZnJNbxzE6iTl0zGKo8fjzV7OaWEDI8UQ+JjgGWaNngXMJ1X9sGCoCCWJA9allDKhJujSPwsNyyFZEcdMIw725aMy5x7IHhCuigHCYk4mz/zjzzaeXasomh20zYkFiytA/PwMDeVt/BRmV+k8ydKtzBeBEApP7c2KrkkUwD1YBcylktenQ5EOcNjidgfz7U8UaM2JitaxbZbqH74vDOdsc2dCn026KHdXkIUzVpvj9Q==
