kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAhnsENrWPN2wTv6Q2Tli9zFneW3GCtR7qT4Lnf4h9lSNvgnAVlhxO+NVdlxRt5A5whq82BmcJy1WK94zKqrcaUD6+wf3gwkw06Cvro90L2cP+/65GZKNz5GG03BLPu9STwVutyVKBlCEKlO0W3c9sQA8TbPUc/LlwGh3sgBhl9q5lHShq9TQPwAvBlynJE6Lk0B0nXcoPv/pWf54UTrLn+1Lz4tLw9NXbRJaCmkfqICooYQJVKk2Wa3Vj+YUyUdqgxzqaSbj/7kbPXbZRVfugKRTtzv4nXCUWxXFgt0dco9UimgJK75l0NqGXMQx86rpGI+DP055aq25upqTHIUDCLAWZ6DV27CQTB3mKN3+X6ixXQXH60JFlpDbMrHuiGq9+jgVG+E9YYPLsxZDjf5EnAezHNcKdLBTpoOcWEzQUCc/Hyeb7mBkW3l7EoXUiviL6XWxYGiWs4BXdff2hMqeiJIXilq0unPGfB8GoyuHsm5fRipxpXbI3D28Tznz3j6xV/at2Gl/YwhUCZwVz7jGsZYU2DEQFRTZp0HvriIr3obJyw//h/xklKmgVZcr/ZV/sasPrY8bdLlftz0A78cXeLmtvXNoSHLUVXBCZKu+yx6SdDyxx3PF29/BVHKfMofmHZFKu6+vfdPgtEz1Dw4PB7hcesUWr/jphSlSYmIAZs/EAF6WMC0q91A9YNouOesp3F5JahT8aHUw==
    admin-user: AgASSIWLd3CBwP0TH5dv8PRAeGq1jNwfwbolKf8XbR8S+04sZcbSPCyeiU3cpl211M70x8r5uHMjJHE2ATWCtn+Sh1wS6YT4PFlH1JDRP6iwc7FgXnFf+BaIL0TZrA15Wm5GEJ6YHiVFVCYPaQ0aXUWEj3QO2fkmq5t32bD8YFGfnkhMbK/6WSvBbM4kewQ99PYD0UWIjtiXU1nK7AlbtAk54I3b2dXa+N/4x9BJjftd36fp6S8n3msTTkMvDjN9TEg3p4YYIWyGNj+kGtI2NlxDturNCjbTsWDsBQBQ96Ug+ZfqoUwb8RbvRHW2pVu62v7BqGA+KM1gYVGudYiZ1By74ZlFV3zXu2SJmlY3E3jAlYftGB2N3DrkcZ2gDGVO/YUbYJuCzcx/Nr11izU69UCcyvd75ywObkD1l2KbgQZ7lsgZIEwPO9JKoSWC+A+MCZ3FQTyOd1fVymJOJbCD3CPMFybP1yA30jsVg6ZrZjaWEzzWPhGc4JZj4OlJnLUaumb89lwZRixIbPeTYzip/ylGHawZWJqIC48wQoQ+JpS1ooYy0ivTS34g4a4apMvSokAOSsOlUJvhnhvTFr84uNjNF2o48oKtPlsXShAOEn2WAXTTPf5pM9jHm+glaU37gzuGxX1mdiMucLj1sMC5RY0JPEnfX46IO/YkdOh5g8XFscTAoqCYCi4sEptikHxe6GsbZPkuGA==
