kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCR5t3YSLZD0tZ0HhtUZwhAavBD0RESVkbptewEYrw4wMLhS/cEI4k6u/Il/NEMWjxWppwyd3ypEVmqDlDFw29Sq7Cl1ZJZ65Xis0/NSPO4RGpkrfcS/iTW3xkfl9U23iMzJhG7OVnWeXmToapTd6dYYJtCPxw3nYhvvhzuz92ks9dzle1r3fpdi3uMSOJ0+ehb+jgXgyXltTOiDmO1utww70CkdzHD7frXwbCaqo4Cburu6cQoJsagLsNSf+vd7wQhTmcQN55HOTn7YDMd+BWnOlQyuwguOHMerrP0HJAbcqMwWMPfz2KoAcImheXuWyZI4f62b9yWXM0J0JleXytp6QGkVdViP2Hepykr8pq8j9xP2OAf2DJpks7kg1m6KoDaRSmFqn4hi2CvAU93Jct6OBzcZi3igiewCjJrHdYkmcOAmq6u4aqWEdBOPFJSqjcGJrhKZSXmmxAbJrAcfbjJ8MxjwDc7ejxyJX9dhX6z/PkUYPKtAC5vm3umAywaKKF2t0elrujHgy5QEQmp+IZa40jZf1SjYRx5xPYdjTjFoHLHKn7CHwl+eqD1JBeIHTqE1h3wmN/2a/kgv9/y/h0yJdA34ECC4ax2e6iBvoA8VRfzt5JfDLKX34YEtIQEWRGDCpZClfPfkwyRWAbDG3aRdRRYx0iXJxp8ouDtW5pvhhg3PQq4MNN2EFPA121H1r/Qoed/ceRe8Q==
    admin-user: AgAZHTaIjC/VoOdfPAdszDBfIbdzYPcVxTaHNs7R3EYwX3ztgrZ/KskQWPecEHhIfZ8h3VRspE4sRXhsdEHwoQHln7Q1+1QOBQK0ymA3UphH+gfoSd70AQqxS+Wfp6OTjwbat94zfYQsuiGZg/XEu81Y2EnB+jo84M9PueigabtBtNa97gmTKObPKTczyJJ8D9ZPeOfjeunlksNjUaQ3kZoZAXoNuklXatzcJoNNo8qdsle+Bk1wX//NEn4lCci5u24u+MliPvyBM7Y0/x46R1dQoIvFqMTUyH/uun6nZbHLxi4KQ0UMAmuN62L3ZBYrdm/6BP/bvELPvcZ5i/COl0kBMrlGRj+7ijazeVSXSq/fGgCL0wumBIFIQzjuw3aOd/z99pnBefbIxbK2EYbHhAd48i3qBiS1tEcpUnw8QnI1b5LFWVohbttHbZKCoVDxupao1Skfuc/pMWLXfS6OuDs2PUerMFfZOCfoY4D6wph5nB7AKzCJlkVJGvVSkAQtpR4C09SJt45TqlIdvrCALaSIJpK6zxygG1VhEX5vxh5BVhabvxSzytkMFolgzpsOjUBt54BUaCCPfLJ+EfRm/UHoFGbdb7vmwpfTyj5lrIKd7tZakQbYOplC6ElALyySgLDg65p2Y0QXElTWD21ue8UvJiphWe/t7Weh0P56hXwQiIu+ZuK364sUF2v/OQiHoIDoTQ/3bQ==
